server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres # ✅ Ensure this is correct!
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # ✅ This ensures tables are created automatically
    show-sql: true



